DROP DATABASE railway;

CREATE DATABASE IF NOT EXISTS railway DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE railway;


CREATE TABLE IF NOT EXISTS admin (
    id_admin VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app (
    id_app VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    redirect_url VARCHAR(255) NOT NULL,
    id_admin VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_admin) REFERENCES admin(id_admin)
);

CREATE TABLE IF NOT EXISTS app_image ( 
    id_app_image INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    id_image VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    id_app VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (id_app) REFERENCES app(id_app)
);

CREATE TABLE IF NOT EXISTS role (
    id_role INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    name VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL,
    id_app VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_app) REFERENCES app(id_app)
);

CREATE TABLE IF NOT EXISTS user (
    id_user VARCHAR(255) NOT NULL PRIMARY KEY UNIQUE,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_image (
    id_user_image INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    id_image VARCHAR(512) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    id_user VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (id_user) REFERENCES user(id_user)
);

CREATE TABLE IF NOT EXISTS user_role (
    id_user VARCHAR(255) NOT NULL,
    id_role INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES user(id_user),
    FOREIGN KEY (id_role) REFERENCES role(id_role)
);
